### ISSUE TITLE
Bug - Magento - Spacing underneath insuranceProduct name

### ISSUE THREAD

**Issue by FranklyLars** [franklyinsure/magento-extension#5]
**Description**
There is a spacing between the insurance product name and the text below it when an insurance product is expanded. This does not occur on the first expanded product tho.

**Steps**
1. Go to the magento plugin.
2. Add multiple insurable products to the cart and head to checkout.
3. When you get to the popup, the first product should be expanded. Click on another product to expand that product and collapse the previously expanded product.
4. Here you can see a spacing, which is not present on the first product when expanded.

**Images**
What the first product looks like expanded and what all products should look like expanded:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/1005d0d1-8dbb-46a1-88e6-7392a8331c5d)

What the second product looks like expanded:
![image](https://github.com/franklyinsure/magento-extension/assets/98809354/4ecaac6e-8d30-45f5-aae4-a0cad8f9ca32)

**Comment by stathmos** [comment]
The space is same for both products, and it's due to the quantity field on the right.

![image](https://github.com/franklyinsure/magento-extension/assets/69260507/42f50143-6d2d-48bb-ae0c-05f331833723)

![image](https://github.com/franklyinsure/magento-extension/assets/69260507/1051989c-499f-4172-9f15-f4174fa65c1d)

**Comment by mwFrankly** [comment]
Closing due to design will be replaced with new design
